title: System Conference Deadlines
description: Countdowns to top Systems conference deadlines (forked from AI Deadlines)
author: Tareq Mahmood

original: "aideadlin.es"
domain: "tareqmahmood.github.io"
baseurl: "/sys-deadlines"

twitter_hashtag: ""
github_username: "tareqmahmood"
github_repo: sys-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
